# ===============================
# Application
# ===============================
spring.application.name=client
# ===============================
# PostgreSQL
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/job_platform
spring.datasource.username=ujjwal
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.tool.schema=DEBUG
# =================================================
# EXCHANGES
# =================================================
job.platform.rabbit.exchanges.standard=standard.exchange
job.platform.rabbit.exchanges.critical=critical.exchange
job.platform.rabbit.exchanges.external=external.exchange
# =================================================
# MAIN QUEUES
# =================================================
job.platform.rabbit.standard.queue=standard.queue
job.platform.rabbit.standard.routingKey=standard.queue.key
job.platform.rabbit.standard.dlq=standard.dlq
job.platform.rabbit.standard.dlqRoutingKey=standard.dlq.key
job.platform.rabbit.critical.queue=critical.queue
job.platform.rabbit.critical.routingKey=critical.queue.key
job.platform.rabbit.critical.dlq=critical.dlq
job.platform.rabbit.critical.dlqRoutingKey=critical.dlq.key
job.platform.rabbit.external.queue=external.queue
job.platform.rabbit.external.routingKey=external.queue.key
job.platform.rabbit.external.dlq=external.dlq
job.platform.rabbit.external.dlqRoutingKey=external.dlq.key
# =================================================
# SHARED RETRY QUEUES
# =================================================
job.platform.rabbit.retries.5s.queue=retry.5s.queue
job.platform.rabbit.retries.5s.routingKey=retry.5s.key
job.platform.rabbit.retries.5s.ttl=5000
job.platform.rabbit.retries.30s.queue=retry.30s.queue
job.platform.rabbit.retries.30s.routingKey=retry.30s.key
job.platform.rabbit.retries.30s.ttl=30000
job.platform.rabbit.retries.60s.queue=retry.60s.queue
job.platform.rabbit.retries.60s.routingKey=retry.60s.key
job.platform.rabbit.retries.60s.ttl=60000
job.platform.rabbit.retries.300s.queue=retry.300s.queue
job.platform.rabbit.retries.300s.routingKey=retry.300s.key
job.platform.rabbit.retries.300s.ttl=300000
job.platform.rabbit.retries.1800s.queue=retry.1800s.queue
job.platform.rabbit.retries.1800s.routingKey=retry.1800s.key
job.platform.rabbit.retries.1800s.ttl=1800000
# ===============================
# Redis
# ===============================
#spring.data.redis.host=localhost
#spring.data.redis.port=6379